### ISSUE TITLE
Results - SGD

### ISSUE THREAD

**Issue by kmaasrud** [kmaasrud/vmc-fys4411#44]
Make a function that finds the optimal alpha for a system and prints it. I think we should compile this functionality and upload a binary to Releases - that could be cool.

For the report, we could plot the value of alpha against the iterations done. This could be done for different starting points to prove that we indeed converge on the same value nonetheless.

**Comment by amundmr** [comment]
Closed this in commit: https://github.com/kmaasrud/vmc-fys4411/commit/ee73ad1ba5ee5af2c00c41f9f14e870622348eb6
