### ISSUE TITLE
Brute force Metropolis algorithm

### ISSUE THREAD

**Issue by kmaasrud** [kmaasrud/vmc-fys4411#5]
Implement the Metropolis sampling algorithm

**Comment by kmaasrud** [comment]
I've described the algorithm in [Brain](https://www.kmaasrud.com/brain/metropolis-algorithm).

**Comment by amundmr** [comment]
Working on this rn

**Comment by kmaasrud** [comment]
This is almost done, but we need to investigate how to implement `acceptance_factor` best.
